### ISSUE TITLE
Package breaking with vite v4.0.4

### ISSUE THREAD

**Issue by ulizzle** [xbmlz/vite-plugin-solid-markdown#4]
Here's the stack trace. The version of vite is the one I got from running the typescript-windicss template seen here: https://github.com/solidjs/templates#get-started

```
> ulizzle-dev@0.1.0 dev /Users/owlbear/Work/ulizzle.dev
> vite

failed to load config from /Users/owlbear/Work/ulizzle.dev/vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/@mdx-js+mdx@2.2.1/node_modules/@mdx-js/mdx/index.js from /Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite-plugin-solid-markdown@0.0.5_solid-js@1.6.6+vite@4.0.4/node_modules/vite-plugin-solid-markdown/dist/index.js not supported.
Instead change the require of /Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/@mdx-js+mdx@2.2.1/node_modules/@mdx-js/mdx/index.js in /Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite-plugin-solid-markdown@0.0.5_solid-js@1.6.6+vite@4.0.4/node_modules/vite-plugin-solid-markdown/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at _require.extensions.<computed> [as .js] (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62106:17)
    at Object.<anonymous> (/Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite-plugin-solid-markdown@0.0.5_solid-js@1.6.6+vite@4.0.4/node_modules/vite-plugin-solid-markdown/dist/index.js:49:18)
    at _require.extensions.<computed> [as .js] (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62106:17)
    at Object.<anonymous> (/Users/owlbear/Work/ulizzle.dev/vite.config.ts:34:49)
    at _require.extensions.<computed> [as .js] (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62103:24)
    at loadConfigFromBundledFile (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62111:21)
    at loadConfigFromFile (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61969:34)
    at async resolveConfig (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61590:28)
    at async createServer (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:60910:20)
    at async CAC.<anonymous> (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/cli.js:729:24)
```

**Comment by xbmlz** [comment]
> Here's the stack trace. The version of vite is the one I got from running the typescript-windicss template seen here: https://github.com/solidjs/templates#get-started
> 
> ```
> > ulizzle-dev@0.1.0 dev /Users/owlbear/Work/ulizzle.dev
> > vite
> 
> failed to load config from /Users/owlbear/Work/ulizzle.dev/vite.config.ts
> error when starting dev server:
> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/@mdx-js+mdx@2.2.1/node_modules/@mdx-js/mdx/index.js from /Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite-plugin-solid-markdown@0.0.5_solid-js@1.6.6+vite@4.0.4/node_modules/vite-plugin-solid-markdown/dist/index.js not supported.
> Instead change the require of /Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/@mdx-js+mdx@2.2.1/node_modules/@mdx-js/mdx/index.js in /Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite-plugin-solid-markdown@0.0.5_solid-js@1.6.6+vite@4.0.4/node_modules/vite-plugin-solid-markdown/dist/index.js to a dynamic import() which is available in all CommonJS modules.
>     at _require.extensions.<computed> [as .js] (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62106:17)
>     at Object.<anonymous> (/Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite-plugin-solid-markdown@0.0.5_solid-js@1.6.6+vite@4.0.4/node_modules/vite-plugin-solid-markdown/dist/index.js:49:18)
>     at _require.extensions.<computed> [as .js] (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62106:17)
>     at Object.<anonymous> (/Users/owlbear/Work/ulizzle.dev/vite.config.ts:34:49)
>     at _require.extensions.<computed> [as .js] (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62103:24)
>     at loadConfigFromBundledFile (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62111:21)
>     at loadConfigFromFile (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61969:34)
>     at async resolveConfig (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61590:28)
>     at async createServer (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:60910:20)
>     at async CAC.<anonymous> (file:///Users/owlbear/Work/ulizzle.dev/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/cli.js:729:24)
> ```

Try to add `type: module` in `package. json`
